version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=todo-app
      - POSTGRES_PASSWORD=verysecurepassword01!
      - POSTGRES_DB=todo
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local