apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todoAppApi-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-todo-app-api
                port:
                  number: {{ .Values.todoAppApi.port }}
