spring:
  flyway:
    user: todo-app
    password: verysecurepassword01!
    enabled: true

  datasource:
    username: todo-app
    password: verysecurepassword01!
    url: jdbc:postgresql://localhost:5432/todo
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
