apiVersion: apps/v1
kind: Deployment
metadata:
  name: "todo-app-api"
spec:
  selector:
    matchLabels:
      app: serviceTodoAppApi
  replicas: 1
  template:
    metadata:
      labels:
        app: serviceTodoAppApi
    spec:
      containers:
        - image: { { .Values.todoAppApi.image } }
          imagePullPolicy: Always
          name: "todo"
          ports:
            - containerPort: { { .Values.todoAppApi.port } }
              protocol: TCP
