apiVersion: apps/v1
kind: Deployment
metadata:
  name: "postgres"
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:15-alpine
          imagePullPolicy: Always
          name: "postgres"
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: {{.Values.db.username}}
            - name: POSTGRES_PASSWORD
              value: {{.Values.db.password}}
            - name: POSTGRES_DB
              value: {{.Values.db.name}}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-volume
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: psql-claim

