apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbpv
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: {{ .Values.db.datafolder }}