apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-claim
spec:
  storageClassName: hostPath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      app: postgres
