name: build-todo-app-api

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: java -version
      - run: ./mvnw clean package
      - run: mvn package
    
      # push container to registry with tag Build-${{ github.run_number}}

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v3

      - run: ls -l

      
      #- working-directory: helm/
      #  run: helm upgrade -i todo-app-api --set todo-app-api.tag=Build-${{ github.run_number}} -n todo-app-api --create-namespace
        
