name: build-todo-app-api

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: kubectl get pods --all --all-namespaces
      - run: helm ls -A